# Generated by Django 5.2.12 on 2026-06-17 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0006_productofavorito'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaReabastecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('stock_bajo', 'Stock Bajo'), ('demanda_alta', 'Demanda Proyectada Alta')], max_length=20)),
                ('stock_actual', models.PositiveIntegerField()),
                ('limite_minimo', models.PositiveIntegerField()),
                ('demanda_proyectada', models.PositiveIntegerField(blank=True, null=True)),
                ('dias_proyectados', models.PositiveIntegerField(blank=True, null=True)),
                ('leida', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_reabastecimiento', to='inventario.varianteproducto')),
            ],
            options={
                'verbose_name': 'Alerta de Reabastecimiento',
                'verbose_name_plural': 'Alertas de Reabastecimiento',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
