# Generated by Django 5.2.12 on 2026-06-17 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloEntrenado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('random_forest', 'Random Forest'), ('prophet', 'Prophet')], max_length=20)),
                ('ruta_archivo', models.CharField(max_length=500)),
                ('fecha_entrenamiento', models.DateTimeField(auto_now_add=True)),
                ('total_registros', models.IntegerField()),
                ('vigente', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Modelo Entrenado',
                'verbose_name_plural': 'Modelos Entrenados',
                'ordering': ['-fecha_entrenamiento'],
            },
        ),
    ]
