# Generated by Django 5.2.12 on 2026-05-12 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0002_codigorecuperacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitacoraAuditoria',
            fields=[
                ('id_bitacora', models.BigAutoField(db_column='id_bitacora', primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('entidad', models.CharField(max_length=100)),
                ('detalles', models.CharField(max_length=500)),
                ('accion', models.CharField(max_length=100)),
                ('usuarios_id', models.BigIntegerField(db_column='usuarios_id')),
            ],
            options={
                'verbose_name': 'Bitacora de auditoria',
                'verbose_name_plural': 'Bitacoras de auditoria',
                'db_table': '"auditoria"."bitacora"',
                'ordering': ['-fecha', '-hora', '-id_bitacora'],
                'managed': False,
            },
        ),
    ]
