# Generated by Django 5.2.12 on 2026-05-16 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0003_bitacoraauditoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codigorecuperacion',
            options={'ordering': ['-creado_en'], 'verbose_name': 'Codigo de Recuperacion', 'verbose_name_plural': 'Codigos de Recuperacion'},
        ),
    ]
