# Generated by Django 5.2.12 on 2026-06-25 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0006_bitacora_por_tenant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['-date_joined'], 'permissions': [('view_dashboard', 'Puede ver el dashboard')], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
    ]
