# Generated by Django 5.2.12 on 2026-06-25 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0007_alter_usuario_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['-date_joined'], 'permissions': [('view_dashboard', 'Puede ver el dashboard'), ('view_backup', 'Puede ver backup y restore'), ('add_backup', 'Puede hacer backup'), ('add_restore', 'Puede hacer restore'), ('add_reporte', 'Puede realizar reportes'), ('add_prediccion', 'Puede realizar predicciones'), ('change_empresa', 'Puede configurar la empresa'), ('view_mi_suscripcion', 'Puede ver la suscripcion'), ('change_mi_suscripcion', 'Puede cambiar la suscripcion')], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
    ]
