# Generated by Django 5.2.12 on 2026-05-16 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['nombre'], 'permissions': [('view_catalogo', 'Puede ver el catalogo')], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
    ]
