# Generated by Django 5.2.12 on 2026-04-09 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='multimedio',
            options={'ordering': ['orden'], 'verbose_name': 'Multimedio', 'verbose_name_plural': 'Multimedios'},
        ),
        migrations.AddField(
            model_name='multimedio',
            name='archivo_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='multimedio',
            name='es_principal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='multimedio',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='multimedio',
            name='tipo',
            field=models.CharField(choices=[('imagen', 'Imagen'), ('realidad_aumentada', 'Realidad Aumentada')], max_length=20),
        ),
    ]
