# Generated by Django 5.2.12 on 2026-05-16 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_producto_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['nombre'], 'permissions': [('view_catalogo', 'Puede ver el catalogo'), ('view_producto_detalle', 'Puede ver detalle de producto')], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
    ]
