# Generated by Django 5.2.12 on 2026-05-24 14:03

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_producto_options'),
    ]

    operations = [
        migrations.RunSQL(
            "CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA public",
        ),
        migrations.RunSQL(
            "SELECT set_config('search_path', current_schema() || ',public', false)",
        ),
        migrations.AddField(
            model_name='producto',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1024, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='embedding_sync_status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('failed', 'Fallido')], default='pending', max_length=20),
        ),
    ]
