# Generated by Django 5.2.12 on 2026-05-10 11:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('precio_mensual', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('precio_anual', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('limite_usuarios', models.IntegerField(default=5)),
                ('limite_productos', models.IntegerField(default=50)),
                ('limite_clientes', models.IntegerField(default=100)),
                ('limite_proveedores', models.IntegerField(default=10)),
                ('feature_realidad_aumentada', models.BooleanField(default=False)),
                ('feature_fotos_3d', models.BooleanField(default=False)),
                ('feature_reportes_dinamicos', models.BooleanField(default=False)),
                ('feature_backup_automatico', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Planes',
            },
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('trial', 'Trial'), ('pausada', 'Pausada'), ('cancelada', 'Cancelada'), ('expirada', 'Expirada')], default='trial', max_length=20)),
                ('ciclo', models.CharField(choices=[('mensual', 'Mensual'), ('anual', 'Anual')], default='mensual', max_length=20)),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('auto_renovar', models.BooleanField(default=True)),
                ('ultima_renovacion', models.DateTimeField(blank=True, null=True)),
                ('cancelada_en', models.DateTimeField(blank=True, null=True)),
                ('cancelada_por', models.CharField(blank=True, max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suscripciones', to='empresas.empresa')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suscripciones', to='empresas.plan')),
            ],
            options={
                'verbose_name': 'Suscripcion',
                'verbose_name_plural': 'Suscripciones',
            },
        ),
        migrations.CreateModel(
            name='SuscripcionCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cambiado_en', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.CharField(blank=True, max_length=255)),
                ('plan_anterior', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cambios_desde', to='empresas.plan')),
                ('plan_nuevo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cambios_hacia', to='empresas.plan')),
                ('suscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios', to='empresas.suscripcion')),
            ],
            options={
                'verbose_name': 'Cambio de suscripcion',
                'verbose_name_plural': 'Cambios de suscripcion',
            },
        ),
        migrations.AddConstraint(
            model_name='suscripcion',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'activa')), fields=('empresa',), name='unique_suscripcion_activa_por_empresa'),
        ),
    ]
